---
- name: Install Django and its dependencies
  hosts: localhost
  become: yes
  become_user: root
  gather_facts: yes

  pre_tasks:
    - name: Check if the OS is Debian-based
      assert:
        that: "'Debian' in ansible_facts.os_family"
        fail_msg: "The Operating System is **not** Debian based ({{ ansible_facts.os_family }})!"
        success_msg: "The Operating System is Debian based, All good !"

    - name: Update the system (update, upgrade, clean, remove)
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes

  tasks:
    - name: Install some packages
      apt:
        state: latest
        name:
          - python3
          - python3-pip
          - python3-pymysql
          - apache2
          - php
          - libapache2-mod-php
          - libapache2-mod-wsgi
          - mariadb-server
          - php-mysql
          - php-curl
          - php-gd
          - php-intl
          - php-json
          - php-mbstring
          - php-xml
          - php-zip

    - name: Start and enable apache2 and mariadb
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - apache2
        - mysql

    - name: Create a mysql user (admin:admin)
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: ""
        name: admin
        password: admin
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Install Django (pip)
      pip:
        name: django
